package in.aqel.blogger;

public class DataCollections_bloggers {
    public final static String bloggerNameEn[] = {
            "Basheer Vallikunnu",
            "Faisal Babu",
            "Akbar Ali",
            "Rosili Joy",
            "Ramji Patteppaadam",
            "Fathima Mubeen",
            "Siyaf AbdulKhadir",
            "Joselet M Joseph",
            "Jefu Jailaf",
            "Rakesh Manoharan",
            "Varikal",
            "Riaz Rafeeque",
            "Sudheer Das",
            "Sangeeth",
            "Pradeed Kumar",
            "Varshini Vinodini",
            "Muralee Mukundan",
            "Reema Ajoy",
            "Philip Verghese Ariel",
            "Mini PC",
           // "Berly Thomas",
            "Echmukutty",
            "Imthiyaz TK",
            "Mohammed yousef"
    };
    public final static String bloggerNameMal[]= {
            "ബഷീർ വള്ളിക്കുന്ന് ",
            "ഫൈസൽ ബാബു",
            "അക്ബർ അലി ",
            "റോസിലി ജോയ് \t",
            "റാംജി പട്ടേപ്പാടം ",
            "മുബി",
            "സിയാഫ് അബ്ദുല്‍ഖാദിര്‍",
            "ജോസ്‌ലറ്റ്‌ എം ജോസഫ്‌	“",
            "ജെഫു ജൈലാഫ്",
            "രാകേഷ് മനോഹരന്‍  ",
            "വരികൾ ",
            "റിയാസ് റഫീക്ക്",
            "സുധീര്‍ദാസ്",
            "സംഗീത്",
            "പ്രദീപ് കുമാർ",
            "വര്‍ഷിണി വിനോദിനി",
            "മുരളീമുകുന്ദൻ",
            "റീമ അജോയ്",
            "ഫിലിപ്പ് വര്‍ഗ്ഗീസ് ഏരിയല്‍",
            "മിനി.പി.സി",
            //  "ബെർളി തോമസ്‌ ",
            "എച്മുക്കുട്ടി",
            "ഇംതിയാസ്",
            "മുഹമ്മദ്‌  യുസുഫ്"

    };
    public final static String blogNameEn[] = {
            "Vallikunnu",
            "Oorkadavu",
            "Chaliyar",
            "Rosapookkal",
            "Kadhakal",
            "Daily Scribbles",
            " Aamiyude Chithrapusthakam",
            " Punjappadam",
            "Cherunnidam",
            "My Movie",
            "Varikalkkidayil ",
            "Butterfly Effect",
            "Sudheerdas",
            "Sangeeth Writes",
            "Short Sights",
            "Unarthublog",
            "Bilathipattanam",
            "Allipazhangal",
            "Arielinte Kurippukal",
            "Ulprerakangal",
            //  "Berlytharangal",
            "Echmuvodu Ulakam",
            "Aachaaryan",
            "Benjjaali"

};
    public final static String blogNameMal[] = {
            "വള്ളിക്കുന്ന്  ",
            "ഊർക്കടവ് ",
            "ചാലിയാർ",
            "റോസാപ്പൂക്കള്‍",
            "കഥകള്‍\t",
            "ദേശാന്തര കാഴ്ചകള്‍",
            "ആമിയുടെ ചിത്രപുസ്തകം",
            "പുഞ്ചപ്പാടം",
            "ചേരുന്നിടം",
            "എന്‍റെ സിനിമ",
            "വരികള്‍ക്കിടയില്‍",
            "ബട്ടര്‍ഫ്ലൈ എഫക്റ്റ്",
            "സുധീര്‍ദാസ്",
            "സംഗീത് റൈറ്റ്സ്",
            "ഷോർട്ട് സൈറ്റ്സ്",
            "പെയ്തൊഴിയാന്‍      ",
            "ബിലാത്തി പട്ടണം",
            "ആലിപ്പഴങ്ങള്‍",
            "ഏരിയലിന്റെ കുറിപ്പുകള്‍",
            "ഉള്‍പ്രേരകങ്ങള്‍",
            //   "ബെർളിത്തരങ്ങൾ",
            "എച്മുവോട് ഉലകം",
            "ആചാര്യന്‍",
            "ബെഞ്ചാലി"
    };
    public final static String description[] = {
            "Basheer Vallikkunnu\n" +
                    "Writer, Blogger & Journalist\n" +
                    "In active blogging from 2007\n" +
                    "Major Awards Received - Samskruthi Award 2008, Super Blogger Award 2010, New Media Award 2013\n" +
                    "Book Published: ഫലസ്തീൻ: പോരാട്ടത്തിന്റെ നാൾവഴി",
            "ഞാന്‍  ഫൈസല്‍ ബാബു !.മലപ്പുറം -കോഴിക്കോട് ജില്ലകള്‍ അതിര്‍ത്തി പങ്കിടുന്ന ഊര്‍ക്കടവില്‍ നിന്നും  സൌദി അറേബ്യയിലെ  കടലോര പട്ടണമായ  ഖുന്‍ഫുദയിലേക്ക്  ഉപജീവനം തേടി പുറപ്പെട്ട   ഒരു നാട്ടുംമ്പുറത്തുകാരന്‍. പ്രവാസ ജീവിതത്തിലെ അനുഭവങ്ങള്‍ വരികളായി വായനക്കാരിലെത്തിക്കാനുള്ള എളിയ ശ്രമമാണ്  ഊര്‍ക്കടവ്  ബ്ലോഗ്.",
            "മലപ്പുറം കോഴിക്കോട് ജില്ലകള്‍ അതിര്‍ത്തി പങ്കിടുന്ന ചാലിയാര്‍ തീരത്ത്, ഹരിത മനോഹരമായ ഒരു വാഴക്കാടന്‍ ഉള്‍ഗ്രാമത്തില്‍ ജനനം. കളിച്ചും ചിരിച്ചും അല്ലലില്ലാതെ വളര്‍ന്ന ബാല്യ കൗമാരങ്ങള്‍ക്കുമേൽ ജീവിത യാഥാര്‍ത്ഥ്യങ്ങളുടെ ഉഷ്ണക്കാറ്റ് വീശിത്തുടങ്ങിയപ്പോള്‍ പ്രവാസത്തിന്റെ യാന്ത്രിക ജീവിതത്തിലേക്ക് വഴുതിപ്പോയ യൗവ്വനം. ഇപ്പോള്‍ സൗദി അറേബ്യയില്‍ ജീവിതത്തിന്‍റെ ഭാഗധേയം തേടി പ്രവാസം തുടരുന്നു. ",
            "ഞാന്‍ റോസിലി. വായന എന്റെ ജീവന്‍, എഴുത്ത് എന്റെ ഇഷ്ടം, എന്റെ പ്രീയപ്പെട്ടവര്‍ എനിക്കെല്ലാം. വിലാസം, rosappookkals@yahoo.com",
            "വെറും ഒരു സാധാരണക്കാരന്‍. പ്രവാസജീവിതത്തില്‍ കുരുങ്ങി കറങ്ങിത്തിരിയുന്നു. വര്‍ഷങ്ങളായി സൗദി അറേബ്യയിലെ റിയാദില്‍. അല്പം വരയും കുറിയും..\t",
            "പാലക്കാട്‌ ജില്ലയിലെ പട്ടാമ്പിയാണ് സ്വദേശം. പ്രവാസത്തിന്റെ പാതി സൗദിയുടെ തലസ്ഥാനമായ റിയാദില്‍. ഇപ്പോള്‍ മഞ്ഞ് പെയ്യുന്ന കാനഡയിലാണ്. യാത്ര തുടരുന്നു...",
            "യാത്രക്കിടയിലെ വിചാരങ്ങള്‍ ,എഞ്ചിന്‍ റൂമിലെ കണ്ണാടിയിലൂടെ , ജോലി ലോകോ പൈലറ്റ്",
            "സിനിമയും പുസ്തകങ്ങളും ഇഷ്ടപ്പെടുന്ന ഒരു സാധാരണക്കാരന്‍",
            "സ്വദേശം : തൃശൂര്‍ ജില്ലയിലെ ചേര്‍പ്പ്‌ ഇപ്പോള്‍ ദുബായിലെ ഒരു മീഡിയ ഗ്രൂപ്പില്‍ ഡിസൈനര്‍ ആയി ജോലി ചെയ്യുന്നു",
            "ലോക സിനിമകള്‍ കാണാന്‍ താല്‍പ്പര്യം ഉള്ള ഒരു കോട്ടയം നിവാസി.എല്ലാം B Tech ബിരുധധാരിയെയും പോലെ സിനിമ എന്ജിനീയറിംഗ് പഠിക്കുന്ന സമയത്ത് തലയില്‍ കയറിയ ആള്‍.നല്ല സിനിമകള്‍ കാണുക പ്രത്യേകിച്ചും ത്രില്ലറുകള്‍ ആണ് ഇഷ്ട ജോണര്‍.എഴുത്തിന്‍റെ സുഖത്തെക്കാളും കാണുന്ന സിനിമകള്‍ സുഹൃതുകലുമായി പങ്കു വയ്ക്കാന്‍ താല്‍പ്പര്യപ്പെടുന്നു",
            "ബ്ലോഗു പോസ്റ്റുകളിലൂടെ ഒരു വേറിട്ട വായന നടത്താനുള്ള ശ്രമം.",
            "കോട്ടയം ജില്ലയിലെ തലയോലപ്പറബ് സ്വദേശം...ഇപ്പോള്‍ മുംബൈയില്‍ ജോലി\t",
            "വഴിയരുകിലിരുന്ന്‌ കൗതുകത്തോടെ കാഴ്‌ചകള്‍ കാണുന്ന ഒരാള്‍. അങ്ങോട്ടും ഇങ്ങോട്ടും കടന്നു പോകുന്ന അതിവേഗ കാഴ്‌ചകള്‍. കുറേക്കഴിഞ്ഞപ്പോള്‍ തിരിച്ചറിഞ്ഞു, ഞാനും യാത്രയിലാണ്‌. കാലത്തിന്റെ ചക്രങ്ങളില്‍ ഉരുളുന്ന, ജീവിതമാകുന്ന അത്ഭുത പേടകത്തിനുള്ളില്‍, പുറകിലേക്കോടിപ്പോയ ഹൃദയ സ്‌പര്‍ശിയായ കാഴ്‌ചകള്‍ക്കും മുന്നോട്ടുള്ള വഴിയില്‍ കാത്തിരിക്കുന്ന അപ്രതീക്ഷിത കാഴ്‌ചകള്‍ക്കും, ഇടയിലൂടെയുള്ള വിസ്‌മയകരമായ ഈ യാത്രയില്‍ കാണുവാനിടയായ (കണ്ണുകള്‍ കൊണ്ടുമാത്രമല്ല) ചിലതെല്ലാം ഇവിടെ കുറിച്ചിടുന്നു. എന്നേപ്പോലെ നിങ്ങളും തിരക്കുള്ള ഒരു യാത്രികനാണ്‌ എന്നറിയാം. അതുകൊണ്ടുതന്നെ ഈ സന്ദര്‍ശനത്തിന്‌ വളരെയധികം നന്ദി.",
            "സംഗീത്.കെ. പാലക്കാട് സ്വദേശി. ഇപ്പോൾ ഒരു സ്വകാര്യ കമ്പനിയിൽ എഞ്ചിനീയറായി ജോലി ചെയ്യുന്നു.",
            "കോഴിക്കോട് സ്വദേശി. അദ്ധ്യാപകൻ-http://www.nizhalukalblog.blogspot.in/ എന്ന ഈ ബ്ലോഗിലും എഴുതുന്നു ",
            "നിന്നെ പ്രതീക്ഷിച്ചു ഞാന് പ്രണയമേ “.. എന്ന് പറയാനാവാതെ അരണ്ട വെട്ടത്തില്… അപരിചിത വഴികളിലൂടെയുള്ള അലച്ചലുകള് വിയര്പ്പ് പൊടിയ്ക്കുന്നൂ… പിന്നെ പിന്നെ ആര്ക്കും കാത്ത് നില്ക്കാതെയായി…!",
            "A Mandan in London ..! ലണ്ടനിൽ ഒരു മണ്ടൻ ... ! ഗൃഹാതുരത്വം തേടിയലയും കേവലം ബഹുമലയാളികളില്‍ ഒരുവന്‍ ഞാൻ ! അതെ.. ശീമ അല്ലെങ്കില്‍ ബിലാത്തി എന്ന് നമ്മള്‍ പണ്ടേ വിളിച്ചു പോന്നിരുന്ന ഇംഗ്ലണ്ട് .. അതിലുള്ള ഏറ്റവും വലിയ പട്ടണം ആകുന്നു ലണ്ടന്‍ അഥവാ ബിലാത്തി പട്ടണം ! അതായത് , എന്റെ തട്ടകം ബിലാത്തിപട്ടണം",
            "അക്ഷരങ്ങളോടാണെന്‍റെ സൗഹൃദം, കവിതയോടാണെന്‍റെ പ്രണയം....",
            "A blogger from Valanjavattom(Thiruvalla) now based at Secunderabad, Telengana.",
            "ജന്തു ശാസ്ത്രത്തില്‍ ബിരുദം,തത്വ ശാസ്ത്രത്തില്‍ ബിരുദാനന്തര ബിരുദം. ആനുകാലികങ്ങളില്‍ ചെറുകഥ, കവിത എന്നിവ എഴുതുന്നു. ഫാര്മസ്യൂട്ടിക്കല്‍ മേഖലയില്‍ ജോലി ചെയ്യുന്നു.സര്‍ഗവേദി ബുക്സിന്‍റെ പ്രണയഗീതങ്ങള്‍,ദശപുഷ്പങ്ങള്‍ എന്നീ കൂട്ടായ്മ കവിതാസമാഹാരങ്ങളും ,എന്‍റെ കഥകള്‍ എന്ന ചെറുകഥാസമാഹാരവും പ്രസിദ്ധീകരിച്ചിട്ടുണ്ട്.",
            //    "Berly Thomas is the founder of the popular Malayalam blog Berlytharangal. He is a senior journalist and technical writer in Malayala Manorama daily, publishing from Kerala. Berlytharangal ranks # 1 in Kerala and according to the Alexa statistics it ranks # 5464 in India and # 54000 in the World Wide Web.",
            "പേര് കല. ജീവിതം എഴുതി പഠിപ്പിച്ച പാഠങ്ങൾക്കപ്പുറം ഒന്നുമറിയാത്തവൾ.",
            "ഞാന്‍ ഇംതിയാസ് ,, എഴുത്തും വായനയും ഇഷ്ടപെടുന്ന പ്രവാസി . ഇപ്പോള്‍ അന്നം തേടി ഇറാഖില്‍ ",
            "ഞാന്‍ മുഹമ്മദ്‌ യൂസുഫ്. ഇരട്ടകളുടെ നാടായ കൊടിഞ്ഞിയില്‍ നിന്നും ,, ഇപ്പോള്‍  സൌദി അറേബ്യയിലെ ദമാമില്‍ പ്രവാസ ജീവിതം നയിക്കുന്നു.ആനുകാലിക വിഷയങ്ങള്‍ എന്റെ തായ വീക്ഷണത്തിലൂടെയും നിരീക്ഷണത്തിലൂടെയും നോക്കികാണാനുള്ള ശ്രമമാണ് ബെഞ്ചാലി ബ്ലോഗില്‍. ",

    };
    public final static  String phoneNumber[] = {
            "+966 50 255 9726",
            "+966506577642",
            "+966508636322",
            "null",
            "00966 551586882",
            "null",
            "919035534014",
            "971558480228",
            "971505724934",
            "919567826482",
            "966506577642",
            "+918108262619",
            "919947501308",
            "919633211321",
            "919544106061",
            "null",
            "0044 7930 134340",
            "null",
            "919700882768",
            "null",
            //   "null",
            "null",
            "9647507902702",
            "91501435249"
    };
    public final static String gmail[] = {
            "vallikkunnu@gmail.com",
            "faisalbabuk@gmail.com",
            "akbar.ali.3538@facebook.com",
            "rosilijoy@gmail.com",
            "raghavaramji@gmail.com",
            "fatima.mubi@gmail.com",
            "siyafabdulkhadir@yahoo.in",
            "joseletmampra1@gmail.com",
            "jailafpa@yahoo.co.uk",
            "rashpace40@gmail.com",
            "varikalkkidayil@gmail.com",
            "riaz.rafeeque@gmail.com",
            "itsmezudheer@gmail.com",
            "sangeethk@gmail.com",
            "pradeepchelannur@gmail.com",
            "varshinivinodhini@gmail.com",
            "muralythayyil@gmail.com",
            "reemaajoy@gmail.com",
            "pvariel@gmail.com",
            "blogminipc@gmail.com",
            //   "berly@berlytharangal.in",
            "echmukutty@gmail.com",
            "imthiyaztk@gmail.com",
            "mohd.yoosuf@gmail.com"
    };
    public final static String facebookId[] = {
            "vallikkunnu" ,
            "faisal.babu.7374",
            "akbar.ali.3538",
            "rosili.joy",
            "ramji.patteppaadam",
            "mubeen.hussain.7",
            "siyafabdulkhadir",
            "joseletmampra1",
            "jefujailaf",
            "rakesh.manoharan1",
            "varikalkkidayil",
            "riaz.rafeeque",
            "sudheer.kumar.52459",
            "sangeeth.kunninmel",
            "pradeepchelannur",
            "varshinivinodhini",
            "muralee.mukundan",
            "reema.ajoy",
            "philip.variel",
            "mini.pc.524",
            //   "berlytharangal",
            "echmu.kutty",
            "imthiyaztk",
            "benchali.postman"
    };
    public final static String googlePlus[] = {
            "115687498578590743703",
            "114428535690141984682",
            "103805942713504922361",
            "107367828051392294581",
            "112348875956085174728",
            "103321737991832688904",
            "+siyafabdulkhadir",
            "116155218079867671810",
            "109756112721485442832",
            "111817915950014468849",
            "114428535690141984682",
            "114440336519338730482",
            "117349448346290964972",
            "ThesangeethBlogspot",
            "117574786561790769688",
            "104415819597479060119",
            "101306191767742401073",
            "116303153919065791485",
            "+PVAriel",
            "null",
            //   "+BerlyThomas-berlytharangal",
            "111331205988320976254",
            "+imthiyazteekay",
            "110700179238244241802"
    };
    public final static int weight[] = {10,30,60, 90, 80, 40,110, 120, 200, 210, 70, 150
            , 140, 180, 160, 360, 50, 170, 100, 110, 2000, 150 ,55
    };

    public final static int bloggerId[] = { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
    };

    public final static String blogUrl[] = {
            "http://www.vallikkunnu.com",
            "http://oorkkadavu.blogspot.in",
            "http://chaliyaarpuzha.blogspot.in",
            "http://www.rosappukkal.blogspot.in",
            "http://pattepadamramji.blogspot.com",
            "http://mubidaily.blogspot.ca",
            "http://aamiyudechithrapusthakam.blogspot.in",
            "http://www.punjapadam.blogspot.com",
            "http://www.jailaf.blogspot.com",
            "http://www.movieholicviews.blogspot.in",
            "http://varikalkidayil.blogspot.in",
            "http://butterflysignature.blogspot.in",
            "http://sudheerdas.blogspot.in",
            "http://www.thesangeeth.blogspot.com",
            "http://www.shortsightsblog.blogspot.in",
            "http://unarthu.blogspot.in",
            "http://bilattipattanam.blogspot.co.uk",
            "http://allipazhangal.blogspot.in",
            "http://arielintekurippukal.blogspot.in",
            "http://ulprerakangal.blogspot.in",
            //  "http://www.berlytharangal.in",
            "http://echmuvoduulakam.blogspot.in",
            "http://aacharyan-imthi.blogspot.com",
            "http://benchali.blogspot.com"
    };

    public final static int blogger_photos[] = {
                R.drawable.blooger_photo_1,
                R.drawable.blooger_photo_2,
                R.drawable.blooger_photo_3,
                R.drawable.blooger_photo_5,
                R.drawable.blooger_photo_6,
                R.drawable.blooger_photo_8,
                R.drawable.blooger_photo_9,
                R.drawable.blooger_photo_10,
                R.drawable.blooger_photo_11,
                R.drawable.blooger_photo_13,
                R.drawable.blooger_photo_14,
                R.drawable.blooger_photo_16,
                R.drawable.blooger_photo_17,
                R.drawable.blooger_photo_18,
                R.drawable.blooger_photo_20,
                R.drawable.blooger_photo_varshini,
                R.drawable.blooger_photo_12,
                R.drawable.blooger_photo_15,
                R.drawable.blooger_photo_7,
                R.drawable.blooger_photo_mini,
            //    R.drawable.blooger_photo_berly,
                R.drawable.blooger_photo_echmu,
                R.drawable.blooger_photo_imthiaz,
                R.drawable.blooger_photo_benjaali,
        };


}
